//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailSender
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametrs
    {
        public int ID { get; set; }
        public string NameParam { get; set; }
        public string ValueParam { get; set; }
        public Nullable<int> ID_result { get; set; }
    
        public virtual Results Results { get; set; }
    }
}
